-- CEO AI Marketing OS — Phase 1 RLS
begin;

alter table public.marketing_brands enable row level security;
alter table public.marketing_audience_segments enable row level security;
alter table public.marketing_personas enable row level security;
alter table public.marketing_message_pillars enable row level security;
alter table public.marketing_offers enable row level security;
alter table public.marketing_ctas enable row level security;
alter table public.marketing_brand_rules enable row level security;
alter table public.marketing_campaigns enable row level security;
alter table public.marketing_campaign_hypotheses enable row level security;
alter table public.marketing_content_items enable row level security;
alter table public.marketing_content_versions enable row level security;
alter table public.marketing_ai_jobs enable row level security;
alter table public.marketing_content_assets enable row level security;
alter table public.marketing_compliance_findings enable row level security;
alter table public.marketing_approval_requests enable row level security;
alter table public.marketing_tracking_links enable row level security;
alter table public.marketing_action_items enable row level security;

-- Strategy tables: member read; editor/admin/owner mutate.
do $$
declare t text;
begin
  foreach t in array array[
    'marketing_brands','marketing_audience_segments','marketing_personas',
    'marketing_message_pillars','marketing_offers','marketing_ctas','marketing_brand_rules',
    'marketing_campaigns','marketing_campaign_hypotheses','marketing_content_items',
    'marketing_content_versions','marketing_tracking_links','marketing_action_items'
  ] loop
    execute format('drop policy if exists %I_select on public.%I', t, t);
    execute format('create policy %I_select on public.%I for select to authenticated using (public.is_member(workspace_id))', t, t);
    execute format('drop policy if exists %I_insert on public.%I', t, t);
    execute format('create policy %I_insert on public.%I for insert to authenticated with check (public.can_edit_workspace(workspace_id))', t, t);
    execute format('drop policy if exists %I_update on public.%I', t, t);
    execute format('create policy %I_update on public.%I for update to authenticated using (public.can_edit_workspace(workspace_id)) with check (public.can_edit_workspace(workspace_id))', t, t);
    execute format('drop policy if exists %I_delete on public.%I', t, t);
    execute format('create policy %I_delete on public.%I for delete to authenticated using (public.can_edit_workspace(workspace_id))', t, t);
  end loop;
end $$;

-- AI jobs: authenticated editors may enqueue; only trusted backend workers update job state/output.
drop policy if exists marketing_ai_jobs_select on public.marketing_ai_jobs;
create policy marketing_ai_jobs_select on public.marketing_ai_jobs
for select to authenticated using (public.is_member(workspace_id));

drop policy if exists marketing_ai_jobs_insert on public.marketing_ai_jobs;
create policy marketing_ai_jobs_insert on public.marketing_ai_jobs
for insert to authenticated with check (public.can_edit_workspace(workspace_id));

-- Assets: members read; editors may create metadata for assets belonging to their workspace.
drop policy if exists marketing_content_assets_select on public.marketing_content_assets;
create policy marketing_content_assets_select on public.marketing_content_assets
for select to authenticated using (public.is_member(workspace_id));

drop policy if exists marketing_content_assets_insert on public.marketing_content_assets;
create policy marketing_content_assets_insert on public.marketing_content_assets
for insert to authenticated with check (public.can_edit_workspace(workspace_id));

-- Compliance findings are generated by the trusted backend. Members can read.
drop policy if exists marketing_compliance_findings_select on public.marketing_compliance_findings;
create policy marketing_compliance_findings_select on public.marketing_compliance_findings
for select to authenticated using (public.is_member(workspace_id));

-- Reviewer/admin/owner may mark findings resolved; editors cannot self-clear blocking findings.
drop policy if exists marketing_compliance_findings_update on public.marketing_compliance_findings;
create policy marketing_compliance_findings_update on public.marketing_compliance_findings
for update to authenticated
using (public.can_review_workspace(workspace_id))
with check (public.can_review_workspace(workspace_id));

-- Approval requests: editor can request; reviewer/admin/owner can decide.
drop policy if exists marketing_approval_requests_select on public.marketing_approval_requests;
create policy marketing_approval_requests_select on public.marketing_approval_requests
for select to authenticated using (public.is_member(workspace_id));

drop policy if exists marketing_approval_requests_insert on public.marketing_approval_requests;
create policy marketing_approval_requests_insert on public.marketing_approval_requests
for insert to authenticated with check (
  public.can_edit_workspace(workspace_id)
  and requested_by = auth.uid()
  and status = 'pending'
);

drop policy if exists marketing_approval_requests_update on public.marketing_approval_requests;
create policy marketing_approval_requests_update on public.marketing_approval_requests
for update to authenticated
using (public.can_review_workspace(workspace_id))
with check (public.can_review_workspace(workspace_id));

-- No DELETE policy for jobs, assets, compliance findings or approval history.

commit;
